const STAGE4_BOOKS = {
  "s4-1-1": {
stage: 4,
unit: 1,
book: 1,
title: "House for sale",
words: [
{ en: "house", ko: "집" },
{ en: "for sale", ko: "팔려고 나온, 매물인" },
{ en: "looked at", ko: "살펴보았다" },
{ en: "wallpaper", ko: "벽지" },
{ en: "room", ko: "방" },
{ en: "looked up", ko: "올려다보았다" },
{ en: "chimney", ko: "굴뚝" },
{ en: "bedroom", ko: "침실" },
{ en: "jumped on", ko: "위로 뛰어올랐다" },
{ en: "chair", ko: "의자" },
{ en: "went down", ko: "아래로 갔다, 내려갔다" },
{ en: "garden", ko: "정원" },
{ en: "tree house", ko: "나무집" },
{ en: "climbed", ko: "올라갔다" },
{ en: "pulled down", ko: "끌어내렸다" }
]
},
"s4-1-2": {
stage: 4,
unit: 1,
book: 2,
title: "The New House",
words: [
{ en: "van", ko: "밴" },
{ en: "came", ko: "왔다" },
{ en: "things", ko: "물건들" },
{ en: "a lot of", ko: "많은" },
{ en: "helped", ko: "도와주었다" },
{ en: "put", ko: "넣었다" },
{ en: "go-kart", ko: "고카트" },
{ en: "box", ko: "상자" },
{ en: "goodbye", ko: "안녕" },
{ en: "play", ko: "놀다" },
{ en: "soon", ko: "곧" },
{ en: "went", ko: "갔다" },
{ en: "new", ko: "새로운" },
{ en: "job", ko: "일, 수고" },
{ en: "toys", ko: "장난감들" }
]
},
"s4-1-3": {
stage: 4,
unit: 1,
book: 3,
title: "Come In!",
words: [
{ en: "painting", ko: "페인트칠하는 중인" },
{ en: "door", ko: "문" },
{ en: "came", ko: "왔다" },
{ en: "play", ko: "놀다" },
{ en: "children", ko: "아이들" },
{ en: "house", ko: "집" },
{ en: "wanted", ko: "원했다" },
{ en: "home", ko: "집으로" },
{ en: "a lot of", ko: "많은" },
{ en: "mess", ko: "엉망 / 어질러진 상태" },
{ en: "looked for", ko: "찾았다" },
{ en: "watching", ko: "보고 있는 중인" },
{ en: "television", ko: "텔레비전" },
{ en: "gave", ko: "주었다" },
{ en: "biscuits", ko: "비스킷" }
]
},
"s4-2-1": {
stage: 4,
unit: 2,
book: 1,
title: "The Balloon",
words: [
{ en: "balloon", ko: "풍선" },
{ en: "secret", ko: "비밀" },
{ en: "told", ko: "말했다" },
{ en: "watch", ko: "보다" },
{ en: "wrong", ko: "고장 난" },
{ en: "photocopier", ko: "복사기" },
{ en: "computer", ko: "컴퓨터" },
{ en: "letter", ko: "편지" },
{ en: "idea", ko: "생각" },
{ en: "tickets", ko: "표들" },
{ en: "prize", ko: "상" },
{ en: "ride", ko: "타기" },
{ en: "stream", ko: "개울" },
{ en: "photograph", ko: "사진" },
{ en: "present", ko: "선물" }
]
},
"s4-2-2": {
stage: 4,
unit: 2,
book: 2,
title: "The Camcorder",
words: [
{ en: "camcorder", ko: "캠코더" },
{ en: "race", ko: "달리기 경주" },
{ en: "video", ko: "비디오" },
{ en: "sports day", ko: "운동회" },
{ en: "wedding", ko: "결혼식" },
{ en: "anniversary", ko: "기념일" },
{ en: "showed", ko: "보여주었다" },
{ en: "watched", ko: "보았다" },
{ en: "laughed", ko: "웃었다" },
{ en: "tree house", ko: "나무집" },
{ en: "burglars", ko: "도둑들" },
{ en: "running away", ko: "도망가고 있는" },
{ en: "police", ko: "경찰" },
{ en: "caught", ko: "잡았다" },
{ en: "phone", ko: "전화기" }
]
},
"s4-2-3": {
stage: 4,
unit: 2,
book: 3,
title: "Nobody Got Wet",
words: [
{ en: "boat", ko: "보트" },
{ en: "sat", ko: "앉았다" },
{ en: "pushed", ko: "밀었다" },
{ en: "stuck", ko: "꼼짝 못했다" },
{ en: "pulled", ko: "끌었다" },
{ en: "river", ko: "강" },
{ en: "wet", ko: "젖은" },
{ en: "job", ko: "일" },
{ en: "picnic", ko: "소풍" },
{ en: "began", ko: "시작되었다" },
{ en: "rain", ko: "비" },
{ en: "floated away", ko: "떠내려갔다" },
{ en: "help", ko: "도와주다" },
{ en: "fall in", ko: "빠지다" },
{ en: "home", ko: "집" }
]
},
"s4-2-4": {
stage: 4,
unit: 2,
book: 4,
title: "Poor Old Mum!",
words: [
{ en: "sports day", ko: "운동회" },
{ en: "long jump", ko: "멀리뛰기" },
{ en: "came", ko: "왔다. ~하게 되었다" },
{ en: "first", ko: "1등" },
{ en: "race", ko: "경주" },
{ en: "second", ko: "2등" },
{ en: "third", ko: "3등" },
{ en: "shouted", ko: "소리쳤다" },
{ en: "last", ko: "마지막" },
{ en: "poor", ko: "불쌍한" },
{ en: "disappointed", ko: "실망한" },
{ en: "shame", ko: "안타까운 일" },
{ en: "blindfold", ko: "눈가리개" },
{ en: "surprise", ko: "놀라움" },
{ en: "everyone", ko: "모두" }
]
},
"s4-2-5": {
stage: 4,
unit: 2,
book: 5,
title: "The Wedding",
words: [
{ en: "weadding", ko: "결혼식" },
{ en: "getting married", ko: "결혼하는" },
{ en: "grandparents", ko: "조부모님" },
{ en: "bridesmaid", ko: "신부 옆 역할" },
{ en: "journey", ko: "여행" },
{ en: "pageboy", ko: "결혼식 보조 남자아이" },
{ en: "material", ko: "천" },
{ en: "measurements", ko: "치수" },
{ en: "surprise", ko: "깜짝선물" },
{ en: "joke", ko: "장난" },
{ en: "glad", ko: "기쁜" },
{ en: "video", ko: "영상" },
{ en: "photograph", ko: "사진" },
{ en: "suit", ko: "정장" },
{ en: "danced", ko: "춤췄다" }
]  
}  
};
